image: lorisleiva/laravel-docker

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: secret
  DB_HOST: mysql
  DB_USERNAME: root

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - cp .env.testing .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - php artisan db:seed
    - php artisan passport:install
    - php artisan serve &
    - php artisan test --env=testing

build:
  stage: build
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
  - staging

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: production
    url: https://example.com
  only:
  - production



include:
  - template: Dependency-Scanning.gitlab-ci.yml

include:
  - template: License-Scanning.gitlab-ci.yml
