image: lorisleiva/laravel-docker

services:
  - mysql:5.7

variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: homestead
  DB_HOST: mysql
  DB_USERNAME: root

stages:
  - test

unit_test:
  stage: test
  script:
    - cp .env.test .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - vendor/bin/phpunit
