image: lorisleiva/laravel-docker

services:
  - mysql:5.7

variables:
  DB_HOST: mysql
  MYSQL_DATABASE: homestead
  DB_USERNAME: root
  MYSQL_ROOT_PASSWORD: secret
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

include:
  - template: Dependency-Scanning.gitlab-ci.yml

include:
  - template: License-Scanning.gitlab-ci.yml

stages:
  - build
  - test
  - analyse
  - deploy

build-composer:
  image: lorisleiva/laravel-docker
  stage: build
  script:
    - cp .env.testing.example .env
    - composer install
  only:
    - pull_request
    - push
    - master
  artifacts:
    paths:
      - .env
      - vendor/
      - storage/logs

artisan-test:
  image: lorisleiva/laravel-docker
  stage: test
  script:
    - cp ./.docker/sail/xdebug.ini /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - cp .env.testing.example .env.testing
    - php artisan key:generate
    - php artisan migrate
    - php artisan db:seed
    - php artisan passport:install
    - php artisan queue:work &
    - php artisan serve &
    - php artisan test --env=testing
  only:
    - pull_request
    - push
    - master
  artifacts:
    paths:
      - storage/logs/
  dependencies:
    - build-composer

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
  - staging

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: production
    url: https://example.com
  only:
  - production

sonarcloud-check:
  stage: analyse
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - master
  dependencies:
    - artisan-test


