version: "3"

services:
    php:
        container_name: laravel_rest_php
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - 9000:9000
        depends_on:
            - composer
            - redis
        working_dir: /var/www/html
        user: ubuntu
        links:
            - redis
        networks:
            - laravel_rest_network
    artisan:
        container_name: laravel_rest_artisan
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - composer
            - redis
        working_dir: /var/www/html
        user: ubuntu
        networks:
            - laravel_rest_network
        entrypoint: ['php','artisan']
    nginx:
        container_name: laravel_rest_nginx
        build:
            context: .
            dockerfile: ./.docker/nginx/Dockerfile
        volumes:
            - .docker/nginx/nginx-local.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        ports:
            - 80:80
        links:
            - php
        networks:
            - laravel_rest_network
    composer:
        container_name: laravel_rest_composer
        build:
            context: .
            dockerfile: ./.docker/composer/Dockerfile
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        user: ubuntu
        entrypoint: ['composer']
        networks:
            - laravel_rest_network
    npm:
        image: node:13.7
        container_name: laravel_rest_npm
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
    redis:
        container_name: laravel_rest_redis
        image: bitnami/redis:latest
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - .docker/redis/data:/bitnami/redis/data
        networks:
            - laravel_rest_network
    mysql:
        image: mysql:5.7.29
        container_name: laravel_rest_mysql
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - laravel_rest_network
networks:
    laravel_rest_network:
        driver: bridge
