apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-restful-api-deployment
  labels:
    app: laravel-restful-api-selector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-restful-api-selector
  template:
    metadata:
      labels:
        app: laravel-restful-api-selector
    spec:
      
      containers:
        - name: app
          envFrom:
            - configMapRef:
                name: laravel-restful-api-config
          image: chumheramis/laravel-restful-api:latest
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 15
            tcpSocket:
              port: 80
            timeoutSeconds: 30
          ports:
            - containerPort: 80
          #readinessProbe:
          #  initialDelaySeconds: 10
          #  periodSeconds: 10
          #  tcpSocket:
          #    port: 80
          resources:
            limits:
              cpu: 200m
              memory: 400M
            requests:
              cpu: 100m
              memory: 200M
          volumeMounts:
            - mountPath: /var/www/html
              name: laravel-restful-api-volume
      volumes:
        - name: laravel-restful-api-volume
          hostPath:
            path: ./
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: laravel-restful-api-service
spec:
  selector:
    app: laravel-restful-api-selector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80