name: Laravel
# Triggered when code is pushed to any branch in a repository
on: [push, pull_request]
jobs:
  laravel-test-job:
    runs-on: ubuntu-latest
    environment: testing
    container:
      image: wendyourway/laravel-docker
    env:
      ARTISAN_MIGRATE: "${ARTISAN_MIGRATE:-1}"
      ARTISAN_SEED: "${ARTISAN_SEED:-1}"
      ARTISAN_SERVE: "${ARTISAN_SERVE:-1}"
      GIT_UPDATE: "0"
      SENTRY_LARAVEL_DSN: ${{ secrets.SENTRY_LARAVEL_DSN }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: homestead
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env.testing
      run: php -r "file_exists('.env.testing') || copy('.env.testing.example', '.env.testing');"
    - name: cache config
      run: php artisan config:cache
    - name: Execute tests
      run: php artisan test --env=testing